Repository Maximus253/project1, pull requests merged in 2025-09, with the labels that each got.

#2 Add Index File
  index.html
Labels: page

#4 Add deploy actions
  .github/workflows/deploy.yml
Labels: backend

#41 Replace Margin with Padding
  Style Sheets/master.css
Labels: styling

#42 Add Buttons to Roadmap Pages
  Pages/college.html
  Pages/emailPage.html
  Pages/fields.html
  Pages/jobs.html
  Pages/roadmap.html
  Pages/whatToDoNow.html
  Pages/whyCS.html
  Style Sheets/infoPage.css
  Style Sheets/roadmap.css
Labels: system

#47 Remove Scrolling on Roadmap
  Style Sheets/roadmap.css
Labels: bug
